name: Deploy Website

on:
  push:
    branches:
      - "**"

jobs:
  deploy:
    uses: XMX-TI/infra-workflows/.github/workflows/deploy-orange.yml@main
    secrets: inherit
    with:
      base_domain: ${{ vars.BASE_DOMAIN }}
      
